### DISCUSSION TITLE
Get Nodes Module

### DISCUSSION THREAD

**Discussion by Andyjb8** [jeisenbath/ansible-collection-solarwinds-orion#15] [Show and tell]
I created a custom module to get node data and custom properties from Solarwinds. It accomplishes the same thing as "Export Custom Property Values" from the "Manage Nodes" page in Solarwinds. I needed this because I generate my ansible inventory from my solarwinds node inventory. I have another script that creates my ansible inventory from this csv output from solarwinds. I am sure it can be improved, but wanted to share in case this is something you thought would be useful to include in this collection

```
    - name: GET NODE DATA FROM SOLARWINDS
      solarwinds.orion.orion_get_nodes:
        <<: *solarwinds_info
        csv_file_path: '/var/tmp/node_output.csv' # PATH FOR CSV
      register: result
      delegate_to: localhost
```

orion_get_nodes.py
```
#!/usr/bin/python
# -*- coding: utf-8 -*-

from ansible.module_utils.basic import AnsibleModule
from orionsdk import SwisClient
import csv

DOCUMENTATION = r'''
---
module: orion_get_nodes
short_description: Gets info about Nodes in Solarwinds Orion NPM
description:
    - "Get info about Nodes in Solarwinds Orion NPM, including custom properties."
version_added: "1.0.0"
author: "Andrew Bailey"
options:
    hostname:
        description:
            - The hostname of the Solarwinds Orion server.
        required: true
        type: str
    username:
        description:
            - The username to authenticate with the Solarwinds Orion server.
        required: true
        type: str
    password:
        description:
            - The password to authenticate with the Solarwinds Orion server.
        required: true
        type: str
    csv_file_path:
        description:
            - The path to save the output CSV file.
        required: true
        type: str
'''

def write_to_csv(nodes, csv_file_path):
    headers = nodes[0].keys() if nodes else []
    with open(csv_file_path, 'w', newline='') as file:
        writer = csv.DictWriter(file, fieldnames=headers)
        writer.writeheader()
        for node in nodes:
            writer.writerow(node)

def main():
    argument_spec = dict(
        hostname=dict(type='str', required=True),
        username=dict(type='str', required=True),
        password=dict(type='str', required=True, no_log=True),
        csv_file_path=dict(type='str', required=True) # New parameter
    )
    
    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )
    
    hostname = module.params['hostname']
    username = module.params['username']
    password = module.params['password']
    csv_file_path = module.params['csv_file_path']  # Using the provided path

    swis = SwisClient(hostname, username, password)

    query = """
    SELECT
        N.NodeID, N.Caption, N.IP_Address, N.MachineType, N.Vendor, N.StatusIcon, N.IOSVersion, N.IOSImage, CP.City, CP.Department
    FROM
        Orion.Nodes AS N
        LEFT JOIN Orion.NodesCustomProperties AS CP ON N.NodeID = CP.NodeID
    """

    try:
        results = swis.query(query)
        nodes = results['results']

        write_to_csv(nodes, csv_file_path)

        module.exit_json(changed=False, nodes=nodes)
    except Exception as e:
        module.fail_json(msg="Error querying SolarWinds API: " + str(e))

if __name__ == '__main__':
    main()

```

**Comment by jeisenbath** [comment]
Nice! What might make it more broadly useful might be a more customizable "orion_query" module, with a bool option to write it to a csv? Only tweak I think would be needing a 'query' param for the string, add a bool param for 'csv', and make the csv_path only required if 'csv' is true.

There's other minor things, such as an EXAMPLES and RETURN block to put in, and Ansible guidelines put the imports after the RETURN block (pep-8 will complain, ignore it). If it's included in the collection, you should also use the extends_document_fragment for the orion_auth_options, along with importing the orion_argument_spec from module_utils/orion.py (orion_custom_property should be a fine reference for all those updates).

Also, I think you'll really find use for what I'm cooking up next. I just finished making a dynamic inventory plugin for another collection, and I plan to use that experience to make one for Solarwinds.

**Reply by Andyjb8** [reply]
I know it can be improved, so please make it better/more customizable module as you see appropriate. If it can generate a CSV to do what I need it to do and more that works for me.

Great I look forward to the dynamic inventory plugin. Right now I am able to add nodes to solarwinds that are not yet in my ansible inventory with playbook like this :

```
---
- name: Add Multiple Hosts Dynamically From Prompt
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: "host_list"
      prompt: "Enter a comma-separated list of hostnames and IPs (format: hostname1:ip1,hostname2:ip2,...)"
      private: false

  vars:
    solarwinds_info: &solarwinds_info
      hostname: "{{ solarwinds_server }}"
      username: "{{ solarwinds_user }}"
      password: "{{ solarwinds_password }}"

  tasks:
    - name: Split input into a list
      set_fact:
        split_host_list: "{{ host_list.split(',') }}"

    - name: Add dynamic hosts
      add_host:
        name: "{{ item.split(':')[0] }}"
        ansible_host: "{{ item.split(':')[1] }}"
        groups: dynamically_added_hosts
      loop: "{{ split_host_list }}"


- name: Execute Tasks on Dynamically Added Hosts
  hosts: dynamically_added_hosts
  gather_facts: false

    - name: ADD SNMPv3 node to Solarwinds
      solarwinds.orion.orion_node:
        <<: *solarwinds_info
        state: present
        name: "{{ inventory_hostname }}"
        ip_address: "{{ ansible_host }}"
        polling_method: SNMP
        snmp_version: 3
        snmpv3_username: "{{ snmpv3_user }}"
        snmpv3_auth_key: "{{ snmpv3_auth_pass }}"
        snmpv3_auth_method: "{{ snmpv3_auth }}{{ snmpv3_auth_level }}"
        snmpv3_priv_key: "{{ snmpv3_priv_pass }}"
        snmpv3_priv_method: "{{ snmpv3_priv }}{{ snmpv3_priv_level }}"
        snmpv3_credential_set: "{{ snmpv3_user }}_set"
      delegate_to: localhost
```
