### ISSUE TITLE
Question/Issue Adding Custom Poller

### ISSUE THREAD

**Issue by Andyjb8** [jeisenbath/ansible-collection-solarwinds-orion#16]
I am unable to add a customer Poller to a node with the orion_node_custom_poller module. I have a customer poller defined in "Manage Pollers" named "Cisco 9300 Switch" However I have not been able to add it to a 9300 switch. I can manually add the poller, so I know it is valid. I have tried adding it with the task "custom_poller" value set to "Cisco 9300 Switch" and the 36 character "PollerID" that I found in the <PollerID> </PollerID> field in the "Cisco 9300 Switch.poller" file. Neither added the poller to the node. When the playbook runs, it appear successful as it shows the module args correctly and a status of "changed", but it's not changing anything. When I go to "List Resources" for the node it still says it is using the "Node Details by Solarwinds" at the top of the nodes Details list instead of the "Cisco 9300 Switch" that is lower down in the customer poller list.   Any ideas?

```
- name: Add custom pollers to node
  solarwinds.orion.orion_node_custom_poller:
    hostname: "{{ solarwinds_server }}"
    username: "{{ solarwinds_user }}"
    password: "{{ solarwinds_pass }}"
    name: "{{ node_name }}"
    state: present
    custom_poller: "{{ custom_poller_name }}"
  delegate_to: localhost
```

This issue is sorta related to issue [#12](https://github.com/jeisenbath/ansible-collection-solarwinds-orion/issues/12) in that I don't know the name of the poller to add it.

**Comment by Andyjb8** [comment]
Ok. For a lot of our nodes we use custom pollers defined in manage pollers to get the exact model number of the device instead of the more generic device series name solarwinds pulls by default. Those custom pollers defined under manage pollers do show up under list resources. You can assign the custom poller to the node under list resources or under settings > manage pollers.  I am trying to figure out how I can add those with ansible. 

I am not getting a failure for a poller that doesn't exist


```
    - name: Add Poller
      solarwinds.orion.orion_node_poller:
        <<: *solarwinds_info
        name: "{{ inventory_hostname }}"
        state: present
        poller: fake_poller
        enabled: true

```

```
TASK [Add Poller] ******************************************************************************************************************
task path: /home/andrewba/automation/playbooks/solarwinds/orion_add_poller.yml:16
Friday 15 December 2023  13:53:31 +0000 (0:00:00.066)       0:00:00.066 ******* 
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
<x.x.0.1> ESTABLISH LOCAL CONNECTION FOR USER: andrewba
<x.x.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/andrewba/.ansible/tmp/ansible-local-248495_bs588gt `"&& mkdir "` echo /home/andrewba/.ansible/tmp/ansible-local-248495_bs588gt/ansible-tmp-1702648413.3473573-248509-225883811477917 `" && echo ansible-tmp-1702648413.3473573-248509-225883811477917="` echo /home/andrewba/.ansible/tmp/ansible-local-248495_bs588gt/ansible-tmp-1702648413.3473573-248509-225883811477917 `" ) && sleep 0'
Using module file /home/andrewba/automation/collections/ansible_collections/solarwinds/orion/plugins/modules/orion_node_poller.py
<x.x.0.1> PUT /home/andrewba/.ansible/tmp/ansible-local-248495_bs588gt/tmpv4tm2_rt TO /home/andrewba/.ansible/tmp/ansible-local-248495_bs588gt/ansible-tmp-1702648413.3473573-248509-225883811477917/AnsiballZ_orion_node_poller.py
<x.x.0.1> EXEC /bin/sh -c 'chmod u+x /home/andrewba/.ansible/tmp/ansible-local-248495_bs588gt/ansible-tmp-1702648413.3473573-248509-225883811477917/ /home/andrewba/.ansible/tmp/ansible-local-248495_bs588gt/ansible-tmp-1702648413.3473573-248509-225883811477917/AnsiballZ_orion_node_poller.py && sleep 0'
<x.x.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/andrewba/.ansible/tmp/ansible-local-248495_bs588gt/ansible-tmp-1702648413.3473573-248509-225883811477917/AnsiballZ_orion_node_poller.py && sleep 0'
<x.x.0.1> EXEC /bin/sh -c 'rm -f -r /home/andrewba/.ansible/tmp/ansible-local-248495_bs588gt/ansible-tmp-1702648413.3473573-248509-225883811477917/ > /dev/null 2>&1 && sleep 0'
changed: [RT-01] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "enabled": true,
            "hostname": "server",
            "ip_address": null,
            "name": "RT-01",
            "node_id": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "poller": "fake_poller",
            "state": "present",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "orion_node": {
        "caption": "RT-01",
        "ipaddress": "x.x.0.1",
        "netobjectid": "N:1131",
        "nodeid": 1131,
        "objectsubtype": "SNMP",
        "status": 1,
        "statusdescription": "Node status is Up.",
        "unmanaged": false,
        "unmanagefrom": "1899-12-30T00:00:00+00:00",
        "unmanageuntil": "1899-12-30T00:00:00+00:00",
        "uri": "swis://server/Orion/Orion.Nodes/NodeID=1131"
    }
}
```

**Comment by jeisenbath** [comment]
Right, orion_node_poller currently doesn't have a fail state if you put in an invalid poller name, because I didn't know of a table which listed available pollers (and if this answer hasn't changed in 10 years, there isn't [link](https://thwack.solarwinds.com/products/the-orion-platform/f/orion-sdk/17290/list-of-available-pollers-in-db))

orion_node_custom_poller, on the other hand, can fail with a bad poller name since those are user created and stored in the db.

I could look into adding a step after the module makes the call to create the poller, to make sure it finds it. That will add execution time to the module, but it may not be significant.

The best suggestion I have to find the poller names is to create one node via the web manually, then query the database for the poller names. These are the two tables I know of to query, and the tables that are currently used by the modules.

```
SELECT n.Caption, p.PollerType
from Orion.Nodes n
left join Orion.Pollers as p on p.NetObjectID = n.NodeId
where n.Caption = 'servername'
```

```
SELECT n.Caption, c.CustomPollerName
from Orion.Nodes n
left join Orion.NPM.CustomPollerAssignment as c on c.NodeID = n.NodeID
where n.Caption = 'servername'
```

**Comment by Andyjb8** [comment]
Ok, I did get these two confused initially... so running this query:
```
query = f"""
SELECT n.Caption, p.PollerType
from Orion.Nodes n
left join Orion.Pollers as p on p.NetObjectID = n.NodeId
where n.Caption = '{node_name}'
```


Gives me this:
```
{'Caption': 'RT-01', 'PollerType': 'N.Status.ICMP.Native'}
{'Caption': 'RT-01', 'PollerType': 'N.Status.SNMP.Native'}
{'Caption': 'RT-01', 'PollerType': 'N.ResponseTime.ICMP.Native'}
{'Caption': 'RT-01', 'PollerType': 'N.ResponseTime.SNMP.Native'}
{'Caption': 'RT-01', 'PollerType': 'N.Details.SNMP.Generic'}
{'Caption': 'RT-01', 'PollerType': 'N.Uptime.SNMP.Generic'}
{'Caption': 'RT-01', 'PollerType': 'N.Routing.SNMP.Ipv4CidrRoutingTable'}
{'Caption': 'RT-01', 'PollerType': 'N.Topology_Layer3.SNMP.ipNetToMedia'}
```

I can successfully add these pollers with this playbook:
```
    - name: Add Poller
      solarwinds.orion.orion_node_poller:
        <<: *solarwinds_info
        name: "{{ inventory_hostname }}"
        state: present
        poller: "{{ item.name }}"
        enabled: "{{ item.enabled }}"
      loop:
        - name: N.Routing.SNMP.Ipv4CidrRoutingTable
          enabled: true
        - name: N.Topology_Layer3.SNMP.ipNetToMedia
          enabled: true
        - name: N.Memory.SNMP.NetSnmpReal
          enabled: true
        - name: N.CPU.SNMP.NetSnmpReal
          enabled: true
      delegate_to: localhost
```

This checks the boxes for Routing Table, CPU & Memory and Topology_Layer3 under list resources. I think I got the orion_node_poller. On to the orion_node_custom_poller...

When I run this query:
```
query = f"""
SELECT n.Caption, c.CustomPollerName
from Orion.Nodes n
left join Orion.NPM.CustomPollerAssignment as c on c.NodeID = n.NodeID
where n.Caption = '{node_name}'
"""
```

I get this:

```
admin@ansible:~$ python3 automation/scripts/get_pollers3.py RT-01
{'Caption': 'RT-01', 'CustomPollerName': None}
```

I have my custom poller CSR1000V created, see screenshot:
![image](https://github.com/jeisenbath/ansible-collection-solarwinds-orion/assets/133019254/4e042d44-6fe0-4129-bbb9-5c9055b88c69)

And its assigned to my node

![image](https://github.com/jeisenbath/ansible-collection-solarwinds-orion/assets/133019254/f7c01bfe-5a29-4002-bb2c-b611841794fc)

What I am want to be able to do is assign this CSRV1000V custom poller to nodes (with when condition).  But I if I can't query for it, then that's an issue because the module needs to know where/what poller to add. My playbook doesn't find the custom poller either and gives me an error saying it can't find it as you said.

```
## Add Custom Poller Test Playbook
---
- name: Add Custom Poller Test
  hosts: all
  gather_facts: false

  vars:
    solarwinds_info: &solarwinds_info
      hostname: "{{ solarwinds_server }}"
      username: "{{ solarwinds_user }}"
      password: "{{ solarwinds_password }}"

  tasks:

    - name: Add Poller
      solarwinds.orion.orion_node_custom_poller:
        <<: *solarwinds_info
        name: "{{ inventory_hostname }}"
        state: present
        custom_poller: "CSR100V"
      delegate_to: localhost
```

```
TASK [Add Poller] **************************************************************************************************
task path: /home/admin/automation/playbooks/solarwinds/orion_add_custom_poller.yml:15
Friday 22 December 2023  15:17:33 +0000 (0:00:00.075)       0:00:00.075 ******* 
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: admin
<localhost> EXEC /bin/sh -c 'echo ~admin && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/admin/.ansible/tmp `"&& mkdir "` echo /home/admin/.ansible/tmp/ansible-tmp-1703258253.2274878-277326-180379647007697 `" && echo ansible-tmp-1703258253.2274878-277326-180379647007697="` echo /home/admin/.ansible/tmp/ansible-tmp-1703258253.2274878-277326-180379647007697 `" ) && sleep 0'
Using module file /home/admin/automation/collections/ansible_collections/solarwinds/orion/plugins/modules/orion_node_custom_poller.py
<localhost> PUT /home/admin/.ansible/tmp/ansible-local-277312ytzxdv1l/tmp9h65rza3 TO /home/admin/.ansible/tmp/ansible-tmp-1703258253.2274878-277326-180379647007697/AnsiballZ_orion_node_custom_poller.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/admin/.ansible/tmp/ansible-tmp-1703258253.2274878-277326-180379647007697/ /home/admin/.ansible/tmp/ansible-tmp-1703258253.2274878-277326-180379647007697/AnsiballZ_orion_node_custom_poller.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/admin/.ansible/tmp/ansible-tmp-1703258253.2274878-277326-180379647007697/AnsiballZ_orion_node_custom_poller.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/admin/.ansible/tmp/ansible-tmp-1703258253.2274878-277326-180379647007697/ > /dev/null 2>&1 && sleep 0'
fatal: [RT-01 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "custom_poller": "CSR100V",
            "hostname": "solarwinds",
            "ip_address": null,
            "name": "RT-01",
            "node_id": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "msg": "Custom poller CSR100V not found."
}
        to retry, use: --limit @/home/admin/retry/orion_add_custom_poller.retry
```


Appreciate any help you can provide!
