### ISSUE TITLE
Itempotency issue with monitor interface and regex character

### ISSUE THREAD

**Issue by Andyjb8** [jeisenbath/ansible-collection-solarwinds-orion#17]
I noticed that with the orion_node_interface module, when I have regex expression character in the interface field, idempotency no longer works. For instance I added a "^" at the beginning so that GigabitEthernet would not match TenGigabitEthernet. However with the **^** idempotency doesn't work any more. I had to do this because my playbook was adding interfaces that were not in my "monitor_interfaces" list. In my case it was adding TenGigabitEthernet interfaces that were down and I did not want to monitor. Adding the ^ fixed that issue, but it broke idempotency. It would be nice to be able to re-run this add interfaces to monitor playbook with idempotency working to see which additional interfaces are added vs ones that are already monitored. 

Here is my playbook task, in this example GigabitEthernet1 was already monitored in solarwinds when this was run.
```
  - name: ADD INTERFACES TO SOLARWINDS TO MONITOR
      solarwinds.orion.orion_node_interface:
        <<: *solarwinds_info
        name: "{{ inventory_hostname }}"
        state: present
        interface: "^{{ item }} " 
        regex: true
      loop: "{{ monitor_interfaces }}"
      delegate_to: localhost
```
	  
Yet you can see it is a status of changed (and is in yellow text)
```
changed: [RTR-01 -> localhost] => (item=GigabitEthernet1) => {
    "ansible_loop_var": "item",
    "changed": true,
    "invocation": {
        "module_args": {
            "hostname": "solarwinds",
            "interface": "^GigabitEthernet1 ",
            "ip_address": null,
            "name": "RTR-01",
            "node_id": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "regex": true,
            "state": "present",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "item": "GigabitEthernet1",
    "orion_node": {
        "caption": "RTR-01",
        "ipaddress": "x.x.0.1",
        "netobjectid": "N:1131",
        "nodeid": 1131,
        "objectsubtype": "SNMP",
        "status": 1,
        "statusdescription": "Node status is Up.",
        "unmanaged": false,
        "unmanagefrom": "1899-12-30T00:00:00+00:00",
        "unmanageuntil": "1899-12-30T00:00:00+00:00",
        "uri": "swis://solarwinds/Orion/Orion.Nodes/NodeID=1131"
    }
}
```
If I remove the **^** from the beginning of the interface name in my playbook task.
```
    - name: ADD INTERFACES TO SOLARWINDS TO MONITOR
      solarwinds.orion.orion_node_interface:
        <<: *solarwinds_info
        name: "{{ inventory_hostname }}"
        state: present
        interface: "{{ item }} "
        regex: true
      loop: "{{ monitor_interfaces }}"
      delegate_to: localhost
```
	  
It shows changed: false (and is in green) as it should because it is already added to solarwinds.
```

ok: [RTR-01 -> localhost] => (item=GigabitEthernet1) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "hostname": "solarwinds",
            "interface": "GigabitEthernet1 ",
            "ip_address": null,
            "name": "RTR-01",
            "node_id": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "regex": true,
            "state": "present",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "item": "GigabitEthernet1",
    "orion_node": {
        "caption": "RTR-01",
        "ipaddress": "x.x.0.1",
        "netobjectid": "N:1131",
        "nodeid": 1131,
        "objectsubtype": "SNMP",
        "status": 1,
        "statusdescription": "Node status is Up.",
        "unmanaged": false,
        "unmanagefrom": "1899-12-30T00:00:00+00:00",
        "unmanageuntil": "1899-12-30T00:00:00+00:00",
        "uri": "swis://solarwinds/Orion/Orion.Nodes/NodeID=1131"
    }
}
```
