### ISSUE TITLE
Unable to find module to add CPU & Memory and asset inventory in the collection.

### ISSUE THREAD

**Issue by bhupendersb** [jeisenbath/ansible-collection-solarwinds-orion#36]
Unable to find module to add CPU & Memory and asset inventory in the collection.
![image](https://github.com/user-attachments/assets/b9917286-25dc-43b2-9b09-a76c4e3a3ca5)

![image](https://github.com/user-attachments/assets/0f95f37b-6441-4409-89a1-142345621d73)

**Comment by Andyjb8** [comment]
I am able to add CPU and Memory with the following:

```
- name: Add CPU and Memory Poller
  solarwinds.orion.orion_node_poller:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    name: "{{ inventory_hostname }}"
    state: present
    poller: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
  loop:
    - name: N.Memory.SNMP.NetSnmpReal
      enabled: true
    - name: N.CPU.SNMP.NetSnmpReal
      enabled: true
  delegate_to: localhost
```
