### ISSUE TITLE
Inventory Plugin Question

### ISSUE THREAD

**Issue by Andyjb8** [jeisenbath/ansible-collection-solarwinds-orion#38]
Is there a way you can you use custom properties for creating groups? Adding a custom property "City" to keyed groups wasn't working for me, but Machine type was working

```
---
plugin: solarwinds.orion.orion_nodes_inventory
cache: false
strict: false
orion_hostname: 
orion_username: 
orion_password:

compose:
  ansible_host: IP_Address
hostname_field: Caption
hostvar_fields:
  - IP_Address
  - Vendor
  - MachineType

keyed_groups:
  - key: MachineType
    prefix: ''
    separator: ''

  - key: City
    prefix: ''
    separator: ''
```
