### ISSUE TITLE
Allow for Loading of Environment variables with Inventory plugin

### ISSUE THREAD

**Issue by Andyjb8** [jeisenbath/ansible-collection-solarwinds-orion#45]
I brought this up in Issue #38, but I thought I would open a new issue to track it. I am trying to get the dynamic inventory plugin working in AAP, and if the plugin supported environment variables, that wold allow me to use the credentials defined in AAP and not have to store encrypted solarwinds credentials in the dynamic inventory file.

**Comment by jeisenbath** [comment]
Yes, thanks for opening the issue to track. I was able to implement this actually on another collection actually and it's pretty straightforward. The next release should be pretty small so I plan to put this in the next release.

**Comment by Andyjb8** [comment]
I saw you had some commits for this in devel-2.x. Is it working for you? I pulled down devel-2.x and it wasn't working for me. It wasn't clear to me how the orion_hostname, orion_username and orion_password in the dynamic inventory file can be configured to pull solarwinds-server, solarwinds_username, solarwinds_password from environment group_vars? This wasn't working for me:
orion_hostname: "{{ solarwinds_server }}" 
orion_username: "{{ solarwinds_user }}" 
orion_password:  "{{ solarwinds_password }}"

**Comment by jeisenbath** [comment]
Pulling variables from group vars into dynamic inventory never works because the dynamic inventory script itself loads before anything in group vars loads. To use environment vars, you have to not set them at all, and set them as bash environment variables.

**Comment by Andyjb8** [comment]
I guess I misunderstood environment vars. I was referring to the vars available in ansible group_vars.

The reason I was asking about this is I am trying to get this inventory plugin working in Ansible Automation Platform. 
The plugin works fine with ansible-navigator when the credentials are defined in the file like this:
```
---
plugin: solarwinds.orion.orion_nodes_inventory
cache: true
cache_timeout: 3600 
strict: false

orion_hostname: my_server
orion_username: my_user
orion_password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        <encrypted password>

filter: >
  WHERE StatusIcon != 'Down.gif'
  AND StatusIcon != 'Unmanaged.gif'
  AND ObjectSubType = 'SNMP'

  
compose:
  ansible_host: IP_Address
hostname_field: Caption
hostvar_fields:
  - IP_Address
  - Vendor
  - MachineType

keyed_groups:
  - key: MachineType
    prefix: ''
    separator: ''
```
However AAP is unable to decrypt the orion_password, which is why I wanted the plugin to pull the credential from the environment, meaning a credential in group_vars. I was thinking the credentials defined within AAP would then be available.
I removed the below orion_* vars from the file.
```
orion_hostname: my_server
orion_username: my_user
orion_password: !vault |
```
And I thought if only it could pull the credential I have in group vars, a custom credential with the following field ids:
orion_hostname
orion_username
orion_password

But if AAP works the same as you are saying  in that the group vars are not yet available when the plugin runs, then that is not going to work. 

However I now see you can assign a credential to an inventory source in AAP. So this might be a way to provide the orion_* vars I originally had specified in the hosts_orion.yml. I tried assigned my orion_* custom credential to my inventory source, but I get an error indicating its not finding it.
`No setting was provided for required configuration plugin_type: ansible_collections.solarwinds.orion.plugins.inventory.orion_nodes_inventory setting orion_hostname`

What needs to be done so that this plugin can use the custom credential (with the orion_* fields) assigned to the inventory source in AAP?
