### ISSUE TITLE
Node SNMP Updating and Validation

### ISSUE THREAD

**Issue by LochieP** [jeisenbath/ansible-collection-solarwinds-orion#69]
Hi,

I am currently working on implementing a python solution for migrating nodes from one SNMP credential to another, attempting to support v2 and v3.

With this, I have two questions I am hoping to get some assistance with!

My first question is what would be the optimal way to update the SNMP Credential on a Node, where the User provides just the Credential ID or Community String.

Currently for SNMPv3, I am updating the Orion.NodeSettings instances for the Node by deleting the previous one and creating a new one with the new Credential ID and I am curious to know if this is the ideal way.

My second question is one I am yet to find any solution for. When modifying the SNMP credential, how can I tell that the new SNMP credential is working? I have noticed that when changing from a Good, working SNMP Credential to a Bad SNMP Credential and triggering a PollNow, it may return a False Positive successful Poll as it uses the previous, Good SNMP credential from the cache. 

Id like to know if anyone is aware of a way to either;

1. Test an SNMP credential on a Node to see if it does / will succeed
2. Know what SNMP credential was used to Poll the Node
3. Force a reset of the Cache to ensure the Poll uses the new SNMP credential
4. Any other possible solutions I am unaware of

Thanks!

**Comment by LochieP** [comment]
I have found two paths for potentially testing out whether an SNMP credential will work for a node or not, but cannot get them fully to work:

1. ValidateCredentials Verb in Orion.Discovery
2. StartDiscovery Verb in Orion.Discovery with a Core Plugin Config with the Credential ID we wish to test used, and then analysing the Discovery Result to see

**Comment by jeisenbath** [comment]
In the one example playbook for adding nodes, I have an example task to poll just the node info and check lastsystemuptimepollutc (in the orion db, this is just in Orion.Nodes as LastSystemUpTimePollUtc) as orion_node_info always invokes a PollNow through the swis API. This is for a new node, where you just care about it being populated, however you could use a plugin or ansible fact to get the time, and do a comparison for updated credentials.

**Comment by LochieP** [comment]
Hi, thanks for the replies and help.

Only problem with this method is that Solarwinds Cache's the SNMP Credential used in Polling a Node, so if you were to say do the following;

Have a Node in SW with a Good SNMP Credential -> Update to a Bad SNMP Credential -> Poll

the Poll can still succeed as it uses the old Good SNMP Credential from the Cache for an unknown period, so if I return 10 minutes later and Poll again, it fails

This unfortunately results in False positives and a lot of waiting to try and wait for the cache to refresh...

**Comment by jeisenbath** [comment]
I see, then the ValidateCredentials verb sounds interesting and might be worth invoking in the modules that configure snmp. I think it should also only do it if we enter a changed state, to avoid unnecessary invoking.

I have also, in some playbooks, just called snmpwalk with the command module to get info and that could validate the credentials possibly (although not validate the poller itself can poll, but that's a whole other issue).

This is maybe not for your use case but anyone else reading...but there's also the thought you might consider configuring SNMP with ansible. It would be pretty hard to add the node then with the incorrect credentials.

**Comment by LochieP** [comment]
The ValidateCredentials Verb is quiet confusing however. I have gotten it to 'work' with the following inputs:

swis.invoke('Orion.Discovery', 'ValidateCredentials', node_ip_string, snmp_port_int, "SolarWinds.Orion.Core.Models.Credentials.SnmpCredentialsV3", {"Name": name_of_credential_set_string, "Context": context_of_credential_set_string}, engine_id_int, "SNMP3")

However, it always returns False even if I know for a fact that the given Credential works on the Node :(

**Comment by Andyjb8** [comment]
I create a module that successfully validates SNMPv3 credentials. I had other changes in my pull request and didn't want to include those so I just thought I would paste it here.  Even though we are provisioning the credentials on the devices, we have had issues if a firewall policy is not properly configured causing SNMP to fail and the node not properly getting added. Would you be able to test this out and see if it can be included in the collection?

```
- name: Validate SNMPv3 credentials
  jeisenbath.solarwinds.orion_validate_snmpv3_credentials:
    hostname: "{{ solarwinds_server }}"
    username: "{{ solarwinds_user }}"
    password: "{{ solarwinds_password }}"
    target_ip: "{{ ip_address }}"
    snmpv3_username: "{{ snmpv3_username }}"
    snmpv3_context: ""
    snmpv3_auth_method: "{{ snmpv3_auth_method }}"
    snmpv3_auth_key: "{{ snmpv3_auth_key }}"
    auth_key_is_password: true
    snmpv3_priv_method: "{{ snmpv3_priv_method }}"
    snmpv3_priv_key: "{{ snmpv3_priv_key }}"
    priv_key_is_password: true
  register: validation_result
  delegate_to: localhost
```

Here is output of the task with Failed SNMPV3 validation
```
ok: [FW-01 -> localhost] => {
    "changed": false,
    "credential_details": {
        "auth_method": "SHA1",
        "context": "",
        "priv_method": "AES128",
        "snmp_port": 161,
        "target_ip": "x.x.0.3",
        "username": "snmp_user"
    },
    "debug_info": {
        "api_error": null,
        "method_used": "ValidateCredentials API with direct parameters"
    },
    "invocation": {
        "module_args": {
            "auth_key_is_password": true,
            "credential_name": null,
            "engine_id": 1,
            "hostname": "solarwinds_server",
            "ip_address": null,
            "name": null,
            "node_id": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": "17774",
            "preferred_snmp": "SNMP3",
            "priv_key_is_password": true,
            "snmp_port": 161,
            "snmpv3_auth_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "snmpv3_auth_method": "SHA1",
            "snmpv3_context": "",
            "snmpv3_priv_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "snmpv3_priv_method": "AES128",
            "snmpv3_username": "snmp_user",
            "target_ip": "x.x.0.3",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "verify": false
        }
    },
    "message": "SNMPv3 credentials validation failed for x.x.0.3",
    "validation_result": false
}
```

Here is output of the task with successful SNMPV3 validation
```
ok: [FW-01 -> localhost] => {
    "changed": false,
    "credential_details": {
        "auth_method": "SHA1",
        "context": "",
        "priv_method": "AES128",
        "snmp_port": 161,
        "target_ip": "x.x.0.3",
        "username": "snmp_user"
    },
    "debug_info": {
        "api_error": null,
        "method_used": "ValidateCredentials API with direct parameters"
    },
    "invocation": {
        "module_args": {
            "auth_key_is_password": true,
            "credential_name": null,
            "engine_id": 1,
            "hostname": "solarwinds_server",
            "ip_address": null,
            "name": null,
            "node_id": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": "17774",
            "preferred_snmp": "SNMP3",
            "priv_key_is_password": true,
            "snmp_port": 161,
            "snmpv3_auth_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "snmpv3_auth_method": "SHA1",
            "snmpv3_context": "",
            "snmpv3_priv_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "snmpv3_priv_method": "AES128",
            "snmpv3_username": "snmp_user",
            "target_ip": "x.x.0.3",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "verify": false
        }
    },
    "message": "SNMPv3 credentials validated successfully for x.x.0.3",
    "validation_result": true
}

```

Here is the module
```
`#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2025, Andrew Bailey (@andyjb8)
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: orion_validate_snmpv3_credentials
short_description: Validate SNMPv3 credentials against a target device using SolarWinds Orion
description:
    - "Validates SNMPv3 credentials against a target IP address using the Orion.Discovery ValidateCredentials verb."
    - "This module allows you to test if SNMPv3 credentials will work on a device before applying them."
    - "Returns True if credentials are valid, False otherwise."
version_added: "1.4.0"
author:
    - "Andrew Bailey (@andyjb8)"
options:
    target_ip:
        description:
            - IP address of the target device to validate credentials against
        required: true
        type: str
    snmp_port:
        description:
            - SNMP port number on the target device
        required: false
        type: int
        default: 161
    credential_name:
        description:
            - Name of the SNMPv3 credential set in SolarWinds Orion
            - If not provided, will use the individual credential parameters
        required: false
        type: str
    snmpv3_username:
        description:
            - SNMPv3 username
            - Required if credential_name is not provided
        required: false
        type: str
    snmpv3_context:
        description:
            - SNMPv3 context
        required: false
        type: str
        default: ""
    snmpv3_auth_method:
        description:
            - SNMPv3 authentication method
        choices: [SHA1, MD5, SHA224, SHA256, SHA384, SHA512]
        required: false
        type: str
        default: "SHA1"
    snmpv3_auth_key:
        description:
            - SNMPv3 authentication key/password
        required: false
        type: str
        no_log: true
    auth_key_is_password:
        description:
            - Whether the authentication key is a password (True) or a key (False)
        required: false
        type: bool
        default: true
    snmpv3_priv_method:
        description:
            - SNMPv3 privacy method
        choices: [DES, DES56, AES128, AES192, AES256]
        required: false
        type: str
        default: "AES128"
    snmpv3_priv_key:
        description:
            - SNMPv3 privacy key/password
        required: false
        type: str
        no_log: true
    priv_key_is_password:
        description:
            - Whether the privacy key is a password (True) or a key (False)
        required: false
        type: bool
        default: true
    engine_id:
        description:
            - SNMPv3 engine ID (typically 1 for most devices)
        required: false
        type: int
        default: 1
    preferred_snmp:
        description:
            - Preferred SNMP version
        choices: [SNMP1, SNMP2, SNMP3]
        required: false
        type: str
        default: "SNMP3"
extends_documentation_fragment:
    - solarwinds.orion.orion_auth_options
requirements:
    - orionsdk
    - requests
'''

EXAMPLES = r'''
---
- name: Validate SNMPv3 credentials using existing credential set
  solarwinds.orion.orion_validate_snmpv3_credentials:
    hostname: "{{ solarwinds_server }}"
    username: "{{ solarwinds_user }}"
    password: "{{ solarwinds_password }}"
    target_ip: "192.168.1.100"
    credential_name: "my_snmpv3_creds"
  delegate_to: localhost

- name: Validate SNMPv3 credentials using individual parameters
  solarwinds.orion.orion_validate_snmpv3_credentials:
    hostname: "{{ solarwinds_server }}"
    username: "{{ solarwinds_user }}"
    password: "{{ solarwinds_password }}"
    target_ip: "192.168.1.100"
    snmpv3_username: "snmp_user"
    snmpv3_context: ""
    snmpv3_auth_method: "SHA1"
    snmpv3_auth_key: "auth_password"
    auth_key_is_password: true
    snmpv3_priv_method: "AES128"
    snmpv3_priv_key: "priv_password"
    priv_key_is_password: true
  delegate_to: localhost

- name: Validate credentials with custom port and engine ID
  solarwinds.orion.orion_validate_snmpv3_credentials:
    hostname: "{{ solarwinds_server }}"
    username: "{{ solarwinds_user }}"
    password: "{{ solarwinds_password }}"
    target_ip: "10.0.0.50"
    snmp_port: 1161
    engine_id: 2
    snmpv3_username: "admin_user"
    snmpv3_auth_method: "SHA256"
    snmpv3_auth_key: "strong_auth_pass"
    snmpv3_priv_method: "AES256"
    snmpv3_priv_key: "strong_priv_pass"
  delegate_to: localhost
'''

RETURN = r'''
validation_result:
    description: Result of the credential validation
    returned: always
    type: bool
    sample: true
message:
    description: Descriptive message about the validation result
    returned: always
    type: str
    sample: "SNMPv3 credentials validated successfully"
credential_details:
    description: Details of the credentials that were validated (passwords redacted)
    returned: always
    type: dict
    sample: {
        "username": "snmp_user",
        "context": "",
        "auth_method": "SHA1",
        "priv_method": "AES128",
        "target_ip": "192.168.1.100",
        "snmp_port": 161
    }
'''

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.solarwinds.orion.plugins.module_utils.orion import OrionModule, orion_argument_spec

try:
    import requests
    HAS_REQUESTS = True
    requests.packages.urllib3.disable_warnings()
except ImportError:
    HAS_REQUESTS = False
except Exception:
    raise Exception

try:
    import orionsdk
    from orionsdk import SwisClient
    HAS_ORION = True
except ImportError:
    HAS_ORION = False
except Exception:
    raise Exception


def get_credential_by_name(orion, credential_name):
    """
    Retrieve SNMPv3 credential details by name from SolarWinds Orion
    """
    try:
        # Query for the credential by name
        query = """
        SELECT 
            c.ID,
            c.Name,
            s.Username,
            s.Context,
            s.AuthenticationMethod,
            s.AuthenticationKey,
            s.AuthenticationKeyIsPassword,
            s.PrivacyMethod,
            s.PrivacyKey,
            s.PrivacyKeyIsPassword
        FROM Orion.Credential c
        LEFT JOIN Orion.SNMPv3Credentials s ON c.ID = s.ID
        WHERE c.Name = '{0}' AND c.CredentialType = 'SolarWinds.Orion.Core.Models.Credentials.SnmpCredentialsV3'
        """.format(credential_name)
        
        results = orion.swis_query(query)
        
        if results and len(results) > 0:
            return results[0]
        else:
            return None
            
    except Exception as e:
        raise Exception("Failed to retrieve credential '{0}': {1}".format(credential_name, str(e)))


def build_credential_details(module_params, credential_data=None):
    """
    Build the credential details dictionary for the ValidateCredentials call
    """
    if credential_data:
        # Use credentials from SolarWinds database
        return {
            "Name": credential_data['Username'],
            "Context": credential_data['Context'] or "",
            "AuthenticationMethod": credential_data['AuthenticationMethod'],
            "AuthenticationKey": credential_data['AuthenticationKey'],
            "AuthenticationKeyIsPassword": credential_data['AuthenticationKeyIsPassword'],
            "PrivacyMethod": credential_data['PrivacyMethod'],
            "PrivacyKey": credential_data['PrivacyKey'],
            "PrivacyKeyIsPassword": credential_data['PrivacyKeyIsPassword']
        }
    else:
        # Use credentials from module parameters
        return {
            "Name": module_params['snmpv3_username'],
            "Context": module_params['snmpv3_context'],
            "AuthenticationMethod": module_params['snmpv3_auth_method'],
            "AuthenticationKey": module_params['snmpv3_auth_key'],
            "AuthenticationKeyIsPassword": module_params['auth_key_is_password'],
            "PrivacyMethod": module_params['snmpv3_priv_method'],
            "PrivacyKey": module_params['snmpv3_priv_key'],
            "PrivacyKeyIsPassword": module_params['priv_key_is_password']
        }


def validate_credentials(orion, target_ip, snmp_port, credential_details, engine_id, preferred_snmp):
    """
    Call the Orion.Discovery ValidateCredentials verb
    """
    try:
        result = orion.swis.invoke(
            'Orion.Discovery', 
            'ValidateCredentials',
            target_ip,
            snmp_port,
            "SolarWinds.Orion.Core.Models.Credentials.SnmpCredentialsV3",
            credential_details,
            engine_id,
            preferred_snmp
        )
        return result
    except Exception as e:
        raise Exception("Failed to validate credentials: {0}".format(str(e)))


def main():
    argument_spec = orion_argument_spec()
    argument_spec.update(
        target_ip=dict(required=True, type='str'),
        snmp_port=dict(required=False, type='int', default=161),
        credential_name=dict(required=False, type='str'),
        snmpv3_username=dict(required=False, type='str'),
        snmpv3_context=dict(required=False, type='str', default=""),
        snmpv3_auth_method=dict(
            required=False, 
            type='str', 
            choices=['SHA1', 'MD5', 'SHA224', 'SHA256', 'SHA384', 'SHA512'],
            default='SHA1'
        ),
        snmpv3_auth_key=dict(required=False, type='str', no_log=True),
        auth_key_is_password=dict(required=False, type='bool', default=True),
        snmpv3_priv_method=dict(
            required=False,
            type='str',
            choices=['DES', 'DES56', 'AES128', 'AES192', 'AES256'],
            default='AES128'
        ),
        snmpv3_priv_key=dict(required=False, type='str', no_log=True),
        priv_key_is_password=dict(required=False, type='bool', default=True),
        engine_id=dict(required=False, type='int', default=1),
        preferred_snmp=dict(
            required=False,
            type='str',
            choices=['SNMP1', 'SNMP2', 'SNMP3'],
            default='SNMP3'
        )
    )

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
        mutually_exclusive=[
            ['credential_name', 'snmpv3_username']
        ],
        required_one_of=[
            ['credential_name', 'snmpv3_username']
        ],
        required_if=[
            ['credential_name', None, ['snmpv3_username', 'snmpv3_auth_key']]
        ]
    )

    if not HAS_ORION:
        module.fail_json(msg='orionsdk required for this module')

    if not HAS_REQUESTS:
        module.fail_json(msg='requests required for this module')

    # Initialize Orion connection
    try:
        orion = OrionModule(module)
    except Exception as e:
        module.fail_json(msg='Failed to connect to SolarWinds Orion: {0}'.format(str(e)))

    # Get parameters
    target_ip = module.params['target_ip']
    snmp_port = module.params['snmp_port']
    engine_id = module.params['engine_id']
    preferred_snmp = module.params['preferred_snmp']
    credential_name = module.params['credential_name']

    credential_data = None
    
    # If credential_name is provided, retrieve credentials from SolarWinds
    if credential_name:
        try:
            credential_data = get_credential_by_name(orion, credential_name)
            if not credential_data:
                module.fail_json(msg="Credential '{0}' not found in SolarWinds Orion".format(credential_name))
        except Exception as e:
            module.fail_json(msg="Error retrieving credential '{0}': {1}".format(credential_name, str(e)))

    # Build credential details for validation
    try:
        credential_details = build_credential_details(module.params, credential_data)
    except Exception as e:
        module.fail_json(msg="Error building credential details: {0}".format(str(e)))

    # Check mode - don't actually validate, just return what would happen
    if module.check_mode:
        module.exit_json(
            changed=False,
            validation_result=None,
            message="Check mode: would validate SNMPv3 credentials for {0}".format(target_ip),
            credential_details={
                "username": credential_details.get("Name", ""),
                "context": credential_details.get("Context", ""),
                "auth_method": credential_details.get("AuthenticationMethod", ""),
                "priv_method": credential_details.get("PrivacyMethod", ""),
                "target_ip": target_ip,
                "snmp_port": snmp_port
            }
        )

    # Validate credentials
    try:
        validation_result = validate_credentials(
            orion, 
            target_ip, 
            snmp_port, 
            credential_details, 
            engine_id, 
            preferred_snmp
        )
        
        # Prepare return data (redact sensitive information)
        return_credential_details = {
            "username": credential_details.get("Name", ""),
            "context": credential_details.get("Context", ""),
            "auth_method": credential_details.get("AuthenticationMethod", ""),
            "priv_method": credential_details.get("PrivacyMethod", ""),
            "target_ip": target_ip,
            "snmp_port": snmp_port
        }
        
        if validation_result:
            message = "SNMPv3 credentials validated successfully for {0}".format(target_ip)
        else:
            message = "SNMPv3 credentials validation failed for {0}".format(target_ip)
            
        module.exit_json(
            changed=False,
            validation_result=validation_result,
            message=message,
            credential_details=return_credential_details
        )
        
    except Exception as e:
        module.fail_json(
            msg="Credential validation failed: {0}".format(str(e)),
            target_ip=target_ip,
            snmp_port=snmp_port
        )


if __name__ == '__main__':
    main()`
```

**Comment by jeisenbath** [comment]
I don't know that this needs its own module, but I'll look at taking the functions and adding them to the utils, and then implement the functions in other modules. The validate function should also likely include validating SNMPv2 and WMI credentials.

**Comment by Andyjb8** [comment]
So you are going to look into having the add node module perform this verification and fail adding the node if the verification fails?
Right now our playbook is adding the node and when SNMP doesn't actually work other tasks like adding interfaces do not work. If the playbook could alert to the issue of the SNMP credentials not working prior to adding the node I think that would be preferred.

**Comment by jeisenbath** [comment]
Correct, that's the thought. As long as the validate credentials can be ran prior to actually creating the node, I believe that can maintain idempotence and give more immediate feedback, in the same way the poll_now() function did.

**Comment by jeisenbath** [comment]
I added the new module orion_credential_set for creating and assigning credentials to a node. I also added calling the validate function to orion_node before creating the node, and tested both success and fail states, and it still meets idempotency. The orion_credential_set module does support WMI, but I lack a test node for that still. The last thing I'll work on for this issue is an example playbook I think, since updating a node from ICMP or SNMPv2 to SNMPv3 will take more than one task/module. Thanks for the suggestions and code, and give me feedback if these need more work for what you're trying to accomplish.

**Comment by Andyjb8** [comment]
Creating a new credential set and assigning to an existing node to update the SNMPv3 credentials was successful in my testing. Here is the playbook tasks I used. I created custom credential set names as I need credential setd per site per SNMPv3 auth/priv levels.

```
- name: Set SNMPv3 Credential Set name - Auth/Priv Level Specific
  ansible.builtin.set_fact:
    snmpv3_credential_set: "{{ site_id }}_SNMPv3_{{ snmpv3_auth }}{{ snmpv3_auth_level }}_{{ snmpv3_priv }}{{ snmpv3_priv_level }}"

- name: Create SNMPv3 credential set "{{ snmpv3_credential_set }}"
  jeisenbath.solarwinds.orion_credential_set:
    hostname: "{{ solarwinds_server }}"
    username: "{{ solarwinds_user }}"
    password: "{{ solarwinds_password }}"
    state: present
    type: snmpv3
    credential_name: "{{ snmpv3_credential_set }}"
    snmpv3:
      username: "{{ snmpv3_user }}"
      auth_key: "{{ snmpv3_auth_pass }}"
      auth_method: "{{ snmpv3_auth }}{{ snmpv3_auth_level }}"
      auth_key_is_pwd: true
      priv_key: "{{ snmpv3_priv_pass }}"
      priv_method: "{{ snmpv3_priv }}{{ snmpv3_priv_level }}"
      priv_key_is_pwd: true
  delegate_to: localhost

- name: Validate and assign Credential Set on an existing node
  jeisenbath.solarwinds.orion_credential_set:
    hostname: "{{ solarwinds_server }}"
    username: "{{ solarwinds_user }}"
    password: "{{ solarwinds_password }}"
    state: assigned
    type: snmpv3
    credential_name: "{{ snmpv3_credential_set }}"
    snmpv3:
      username: "{{ snmpv3_user }}"
      auth_key: "{{ snmpv3_auth_pass }}"
      auth_method: "{{ snmpv3_auth }}{{ snmpv3_auth_level }}"
      auth_key_is_pwd: true
      priv_key: "{{ snmpv3_priv_pass }}"
      priv_method: "{{ snmpv3_priv }}{{ snmpv3_priv_level }}"
      priv_key_is_pwd: true
    ip_address: "{{ ansible_host }}"
  delegate_to: localhost

```

For creating a new credential set and using it for adding new nodes, here is are my playbook task that was working for me. It's seem redundant for orion_node module to requires all the snmpv3 vars be defined in addition to just requiring the  snmpv3_credential_set, but I guess that what is required by the Solarwinds API?
```

- name: Set SNMPv3 Credential Set name - Auth/Priv Level Specific
  ansible.builtin.set_fact:
    snmpv3_credential_set: "{{ site_id }}_SNMPv3_{{ snmpv3_auth }}{{ snmpv3_auth_level }}_{{ snmpv3_priv }}{{ snmpv3_priv_level }}"

- name: Create SNMPv3 credential set "{{ snmpv3_credential_set }}"
  jeisenbath.solarwinds.orion_credential_set:
    hostname: "{{ solarwinds_server }}"
    username: "{{ solarwinds_user }}"
    password: "{{ solarwinds_password }}"
    state: present
    type: snmpv3
    credential_name: "{{ snmpv3_credential_set }}"
    snmpv3:
      username: "{{ snmpv3_user }}"
      auth_key: "{{ snmpv3_auth_pass }}"
      auth_method: "{{ snmpv3_auth }}{{ snmpv3_auth_level }}"
      auth_key_is_pwd: true
      priv_key: "{{ snmpv3_priv_pass }}"
      priv_method: "{{ snmpv3_priv }}{{ snmpv3_priv_level }}"
      priv_key_is_pwd: true
  delegate_to: localhost


- name: Add SNMPv3 node to Solarwinds using credential set
  jeisenbath.solarwinds.orion_node:
    hostname: "{{ solarwinds_server }}"
    username: "{{ solarwinds_user }}"
    password: "{{ solarwinds_password }}"
    state: present
    name: "{{ inventory_hostname }}"
    ip_address: "{{ ansible_host }}"
    polling_method: SNMP
    snmp_version: 3
    snmpv3_credential_set: "{{ snmpv3_credential_set }}"
    snmpv3_username: "{{ snmpv3_user }}" # This is still required with snmp_version: 3 even with credential set
    snmpv3_auth_key: "{{ snmpv3_auth_pass }}"  # This is still required with snmp_version: 3 even with credential set
    snmpv3_auth_method: "{{ snmpv3_auth }}{{ snmpv3_auth_level }}"  # Required for validation even with credential set
    snmpv3_priv_key: "{{ snmpv3_priv_pass }}"  # This is still required with snmp_version: 3 even with credential set
    snmpv3_priv_method: "{{ snmpv3_priv }}{{ snmpv3_priv_level }}"  # Required for validation even with credential set
  register: add_node_snmp_response
  delegate_to: localhost
```


Thanks for you work on this!
